import { PokemonSpeciesInfo } from './pokeApi';

export const FALLBACK_POKEMON_DB: Record<string, Partial<PokemonSpeciesInfo>> = {
  // Starters & Evolutions
  '1': {
    id: 1,
    name: 'bulbasaur',
    displayName: 'Bulbasaur',
    types: ['grass', 'poison'],
    baseStats: { hp: 45, attack: 49, defense: 49, spAttack: 65, spDefense: 65, speed: 45 },
    catchRate: 45,
    baseExp: 64,
    evolutions: [{ triggerType: 'level-up', minLevel: 16, targetSpeciesName: 'ivysaur', targetSpeciesId: 2 }],
  },
  '2': {
    id: 2,
    name: 'ivysaur',
    displayName: 'Ivysaur',
    types: ['grass', 'poison'],
    baseStats: { hp: 60, attack: 62, defense: 63, spAttack: 80, spDefense: 80, speed: 60 },
    catchRate: 45,
    baseExp: 142,
    evolutions: [{ triggerType: 'level-up', minLevel: 32, targetSpeciesName: 'venusaur', targetSpeciesId: 3 }],
  },
  '3': {
    id: 3,
    name: 'venusaur',
    displayName: 'Venusaur',
    types: ['grass', 'poison'],
    baseStats: { hp: 80, attack: 82, defense: 83, spAttack: 100, spDefense: 100, speed: 80 },
    catchRate: 45,
    baseExp: 236,
    evolutions: [],
  },
  '4': {
    id: 4,
    name: 'charmander',
    displayName: 'Charmander',
    types: ['fire'],
    baseStats: { hp: 39, attack: 52, defense: 43, spAttack: 60, spDefense: 50, speed: 65 },
    catchRate: 45,
    baseExp: 62,
    evolutions: [{ triggerType: 'level-up', minLevel: 16, targetSpeciesName: 'charmeleon', targetSpeciesId: 5 }],
  },
  '5': {
    id: 5,
    name: 'charmeleon',
    displayName: 'Charmeleon',
    types: ['fire'],
    baseStats: { hp: 58, attack: 64, defense: 58, spAttack: 80, spDefense: 65, speed: 80 },
    catchRate: 45,
    baseExp: 142,
    evolutions: [{ triggerType: 'level-up', minLevel: 36, targetSpeciesName: 'charizard', targetSpeciesId: 6 }],
  },
  '6': {
    id: 6,
    name: 'charizard',
    displayName: 'Charizard',
    types: ['fire', 'flying'],
    baseStats: { hp: 78, attack: 84, defense: 78, spAttack: 109, spDefense: 85, speed: 100 },
    catchRate: 45,
    baseExp: 240,
    evolutions: [],
  },
  '7': {
    id: 7,
    name: 'squirtle',
    displayName: 'Squirtle',
    types: ['water'],
    baseStats: { hp: 44, attack: 48, defense: 65, spAttack: 50, spDefense: 64, speed: 43 },
    catchRate: 45,
    baseExp: 63,
    evolutions: [{ triggerType: 'level-up', minLevel: 16, targetSpeciesName: 'wartortle', targetSpeciesId: 8 }],
  },
  '8': {
    id: 8,
    name: 'wartortle',
    displayName: 'Wartortle',
    types: ['water'],
    baseStats: { hp: 59, attack: 63, defense: 80, spAttack: 65, spDefense: 80, speed: 58 },
    catchRate: 45,
    baseExp: 142,
    evolutions: [{ triggerType: 'level-up', minLevel: 36, targetSpeciesName: 'blastoise', targetSpeciesId: 9 }],
  },
  '9': {
    id: 9,
    name: 'blastoise',
    displayName: 'Blastoise',
    types: ['water'],
    baseStats: { hp: 79, attack: 83, defense: 100, spAttack: 85, spDefense: 105, speed: 78 },
    catchRate: 45,
    baseExp: 239,
    evolutions: [],
  },
  '25': {
    id: 25,
    name: 'pikachu',
    displayName: 'Pikachu',
    types: ['electric'],
    baseStats: { hp: 35, attack: 55, defense: 40, spAttack: 50, spDefense: 50, speed: 90 },
    catchRate: 190,
    baseExp: 112,
    evolutions: [{ triggerType: 'use-item', item: 'thunder-stone', targetSpeciesName: 'raichu', targetSpeciesId: 26 }],
  },
  '26': {
    id: 26,
    name: 'raichu',
    displayName: 'Raichu',
    types: ['electric'],
    baseStats: { hp: 60, attack: 90, defense: 55, spAttack: 90, spDefense: 80, speed: 110 },
    catchRate: 75,
    baseExp: 218,
    evolutions: [],
  },

  // Route 1 & 2 Wilds
  '16': {
    id: 16,
    name: 'pidgey',
    displayName: 'Pidgey',
    types: ['normal', 'flying'],
    baseStats: { hp: 40, attack: 45, defense: 40, spAttack: 35, spDefense: 35, speed: 56 },
    catchRate: 255,
    baseExp: 50,
    evolutions: [{ triggerType: 'level-up', minLevel: 18, targetSpeciesName: 'pidgeotto', targetSpeciesId: 17 }],
  },
  '17': {
    id: 17,
    name: 'pidgeotto',
    displayName: 'Pidgeotto',
    types: ['normal', 'flying'],
    baseStats: { hp: 63, attack: 60, defense: 55, spAttack: 50, spDefense: 50, speed: 71 },
    catchRate: 120,
    baseExp: 122,
    evolutions: [{ triggerType: 'level-up', minLevel: 36, targetSpeciesName: 'pidgeot', targetSpeciesId: 18 }],
  },
  '18': {
    id: 18,
    name: 'pidgeot',
    displayName: 'Pidgeot',
    types: ['normal', 'flying'],
    baseStats: { hp: 83, attack: 80, defense: 75, spAttack: 70, spDefense: 70, speed: 101 },
    catchRate: 45,
    baseExp: 216,
    evolutions: [],
  },
  '19': {
    id: 19,
    name: 'rattata',
    displayName: 'Rattata',
    types: ['normal'],
    baseStats: { hp: 30, attack: 56, defense: 35, spAttack: 25, spDefense: 35, speed: 72 },
    catchRate: 255,
    baseExp: 51,
    evolutions: [{ triggerType: 'level-up', minLevel: 20, targetSpeciesName: 'raticate', targetSpeciesId: 20 }],
  },
  '20': {
    id: 20,
    name: 'raticate',
    displayName: 'Raticate',
    types: ['normal'],
    baseStats: { hp: 55, attack: 81, defense: 60, spAttack: 50, spDefense: 70, speed: 97 },
    catchRate: 127,
    baseExp: 145,
    evolutions: [],
  },
  '10': {
    id: 10,
    name: 'caterpie',
    displayName: 'Caterpie',
    types: ['bug'],
    baseStats: { hp: 45, attack: 30, defense: 35, spAttack: 20, spDefense: 20, speed: 45 },
    catchRate: 255,
    baseExp: 39,
    evolutions: [{ triggerType: 'level-up', minLevel: 7, targetSpeciesName: 'metapod', targetSpeciesId: 11 }],
  },
  '11': {
    id: 11,
    name: 'metapod',
    displayName: 'Metapod',
    types: ['bug'],
    baseStats: { hp: 50, attack: 20, defense: 55, spAttack: 25, spDefense: 25, speed: 30 },
    catchRate: 120,
    baseExp: 72,
    evolutions: [{ triggerType: 'level-up', minLevel: 10, targetSpeciesName: 'butterfree', targetSpeciesId: 12 }],
  },
  '12': {
    id: 12,
    name: 'butterfree',
    displayName: 'Butterfree',
    types: ['bug', 'flying'],
    baseStats: { hp: 60, attack: 45, defense: 50, spAttack: 90, spDefense: 80, speed: 70 },
    catchRate: 45,
    baseExp: 178,
    evolutions: [],
  },
  '13': {
    id: 13,
    name: 'weedle',
    displayName: 'Weedle',
    types: ['bug', 'poison'],
    baseStats: { hp: 40, attack: 35, defense: 30, spAttack: 20, spDefense: 20, speed: 50 },
    catchRate: 255,
    baseExp: 39,
    evolutions: [{ triggerType: 'level-up', minLevel: 7, targetSpeciesName: 'kakuna', targetSpeciesId: 14 }],
  },
  '14': {
    id: 14,
    name: 'kakuna',
    displayName: 'Kakuna',
    types: ['bug', 'poison'],
    baseStats: { hp: 45, attack: 25, defense: 50, spAttack: 25, spDefense: 25, speed: 35 },
    catchRate: 120,
    baseExp: 72,
    evolutions: [{ triggerType: 'level-up', minLevel: 10, targetSpeciesName: 'beedrill', targetSpeciesId: 15 }],
  },
  '15': {
    id: 15,
    name: 'beedrill',
    displayName: 'Beedrill',
    types: ['bug', 'poison'],
    baseStats: { hp: 65, attack: 90, defense: 40, spAttack: 45, spDefense: 80, speed: 75 },
    catchRate: 45,
    baseExp: 178,
    evolutions: [],
  },

  // Nidorans
  '29': {
    id: 29,
    name: 'nidoran-f',
    displayName: 'Nidoran♀',
    types: ['poison'],
    baseStats: { hp: 55, attack: 47, defense: 52, spAttack: 40, spDefense: 40, speed: 41 },
    catchRate: 235,
    baseExp: 55,
    evolutions: [{ triggerType: 'level-up', minLevel: 16, targetSpeciesName: 'nidorina', targetSpeciesId: 30 }],
  },
  '30': {
    id: 30,
    name: 'nidorina',
    displayName: 'Nidorina',
    types: ['poison'],
    baseStats: { hp: 70, attack: 62, defense: 67, spAttack: 55, spDefense: 55, speed: 56 },
    catchRate: 120,
    baseExp: 128,
    evolutions: [{ triggerType: 'use-item', item: 'moon-stone', targetSpeciesName: 'nidoqueen', targetSpeciesId: 31 }],
  },
  '31': {
    id: 31,
    name: 'nidoqueen',
    displayName: 'Nidoqueen',
    types: ['poison', 'ground'],
    baseStats: { hp: 90, attack: 92, defense: 87, spAttack: 75, spDefense: 85, speed: 76 },
    catchRate: 45,
    baseExp: 227,
    evolutions: [],
  },
  '32': {
    id: 32,
    name: 'nidoran-m',
    displayName: 'Nidoran♂',
    types: ['poison'],
    baseStats: { hp: 46, attack: 57, defense: 40, spAttack: 40, spDefense: 40, speed: 50 },
    catchRate: 235,
    baseExp: 55,
    evolutions: [{ triggerType: 'level-up', minLevel: 16, targetSpeciesName: 'nidorino', targetSpeciesId: 33 }],
  },
  '33': {
    id: 33,
    name: 'nidorino',
    displayName: 'Nidorino',
    types: ['poison'],
    baseStats: { hp: 61, attack: 72, defense: 57, spAttack: 55, spDefense: 55, speed: 65 },
    catchRate: 120,
    baseExp: 128,
    evolutions: [{ triggerType: 'use-item', item: 'moon-stone', targetSpeciesName: 'nidoking', targetSpeciesId: 34 }],
  },
  '34': {
    id: 34,
    name: 'nidoking',
    displayName: 'Nidoking',
    types: ['poison', 'ground'],
    baseStats: { hp: 81, attack: 102, defense: 77, spAttack: 85, spDefense: 75, speed: 85 },
    catchRate: 45,
    baseExp: 227,
    evolutions: [],
  },

  // Eevee & Stones
  '133': {
    id: 133,
    name: 'eevee',
    displayName: 'Eevee',
    types: ['normal'],
    baseStats: { hp: 55, attack: 55, defense: 50, spAttack: 45, spDefense: 65, speed: 55 },
    catchRate: 45,
    baseExp: 65,
    evolutions: [
      { triggerType: 'use-item', item: 'water-stone', targetSpeciesName: 'vaporeon', targetSpeciesId: 134 },
      { triggerType: 'use-item', item: 'thunder-stone', targetSpeciesName: 'jolteon', targetSpeciesId: 135 },
      { triggerType: 'use-item', item: 'fire-stone', targetSpeciesName: 'flareon', targetSpeciesId: 136 },
    ],
  },
  '134': {
    id: 134,
    name: 'vaporeon',
    displayName: 'Vaporeon',
    types: ['water'],
    baseStats: { hp: 130, attack: 65, defense: 60, spAttack: 110, spDefense: 95, speed: 65 },
    catchRate: 45,
    baseExp: 184,
    evolutions: [],
  },
  '135': {
    id: 135,
    name: 'jolteon',
    displayName: 'Jolteon',
    types: ['electric'],
    baseStats: { hp: 65, attack: 65, defense: 60, spAttack: 110, spDefense: 95, speed: 130 },
    catchRate: 45,
    baseExp: 184,
    evolutions: [],
  },
  '136': {
    id: 136,
    name: 'flareon',
    displayName: 'Flareon',
    types: ['fire'],
    baseStats: { hp: 65, attack: 130, defense: 60, spAttack: 95, spDefense: 110, speed: 65 },
    catchRate: 45,
    baseExp: 184,
    evolutions: [],
  },
};

// Aliases by name
for (const key of Object.keys(FALLBACK_POKEMON_DB)) {
  const p = FALLBACK_POKEMON_DB[key];
  if (p && p.name) {
    FALLBACK_POKEMON_DB[p.name.toLowerCase()] = p;
  }
}
